CampDios/CampDios/Controllers/HistoriaEspiritualsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class HistoriaEspiritualsController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: HistoriaEspirituals
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Miembros", Permiso = "Lectura")]
        public ActionResult Index()
        {
            var historiaEspiritual = db.HistoriaEspiritual.Include(h => h.Iglesia).Include(h => h.Miembros);
            return View(historiaEspiritual.ToList());
        }

        // GET: HistoriaEspirituals/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Miembros", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HistoriaEspiritual historiaEspiritual = db.HistoriaEspiritual.Find(id);
            if (historiaEspiritual == null)
            {
                return HttpNotFound();
            }
            return View(historiaEspiritual);
        }

        // GET: HistoriaEspirituals/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Miembros", Permiso = "Escritura")]
        public ActionResult Create()
        {
            ViewBag.IglesiaBautismo = new SelectList(db.Iglesia, "IdIglesia", "Nombre");
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres");
            return View();
        }

        // POST: HistoriaEspirituals/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdHistoria,IdMiembro,FechaConversion,FechaBautismo,IglesiaBautismo")] HistoriaEspiritual historiaEspiritual)
        {
            if (ModelState.IsValid)
            {
                db.HistoriaEspiritual.Add(historiaEspiritual);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IglesiaBautismo = new SelectList(db.Iglesia, "IdIglesia", "Nombre", historiaEspiritual.IglesiaBautismo);
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres", historiaEspiritual.IdMiembro);
            return View(historiaEspiritual);
        }

        // GET: HistoriaEspirituals/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Miembros", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HistoriaEspiritual historiaEspiritual = db.HistoriaEspiritual.Find(id);
            if (historiaEspiritual == null)
            {
                return HttpNotFound();
            }
            ViewBag.IglesiaBautismo = new SelectList(db.Iglesia, "IdIglesia", "Nombre", historiaEspiritual.IglesiaBautismo);
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres", historiaEspiritual.IdMiembro);
            return View(historiaEspiritual);
        }

        // POST: HistoriaEspirituals/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdHistoria,IdMiembro,FechaConversion,FechaBautismo,IglesiaBautismo")] HistoriaEspiritual historiaEspiritual)
        {
            if (ModelState.IsValid)
            {
                db.Entry(historiaEspiritual).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IglesiaBautismo = new SelectList(db.Iglesia, "IdIglesia", "Nombre", historiaEspiritual.IglesiaBautismo);
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres", historiaEspiritual.IdMiembro);
            return View(historiaEspiritual);
        }

        // GET: HistoriaEspirituals/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Miembros", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HistoriaEspiritual historiaEspiritual = db.HistoriaEspiritual.Find(id);
            if (historiaEspiritual == null)
            {
                return HttpNotFound();
            }
            return View(historiaEspiritual);
        }

        // POST: HistoriaEspirituals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HistoriaEspiritual historiaEspiritual = db.HistoriaEspiritual.Find(id);
            db.HistoriaEspiritual.Remove(historiaEspiritual);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Views/HistoriaEspirituals/Create.cshtml
@model CampDios.Modelos.HistoriaEspiritual

@{
    ViewBag.Title = "Crear-Historia Espiritual";
}

<center><h2>Crear - Historia espiritual</h2></center>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HistoriaEspiritual</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdMiembro, "IdMiembro", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdMiembro", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdMiembro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaConversion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaConversion, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
                @Html.ValidationMessageFor(model => model.FechaConversion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaBautismo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaBautismo, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
                @Html.ValidationMessageFor(model => model.FechaBautismo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IglesiaBautismo, "IglesiaBautismo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IglesiaBautismo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IglesiaBautismo, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","HistoriaEspirituals")" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CampDios/CampDios/Views/HistoriaEspirituals/Delete.cshtml
@model CampDios.Modelos.HistoriaEspiritual

@{
    ViewBag.Title = "Historia Espiritual - Borrar";
}

<center><h2>Historia Espiritual - Borrar</h2></center>

<h3>¿Esta seguro que desea borrar esta historia espiritual?</h3>
<div>
    <h4>HistoriaEspiritual</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaConversion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaConversion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaBautismo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaBautismo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Iglesia.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Iglesia.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Miembros.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Miembros.Nombres)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> &nbsp;&nbsp;
            <a href="@Url.Action("Index","HistoriaEspirituals")" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
            </a>
        </div>
    }
</div>

CampDios/CampDios/Views/HistoriaEspirituals/Details.cshtml
@model CampDios.Modelos.HistoriaEspiritual

@{
    ViewBag.Title = "Historia Espiritual - Detalles";
}

<center><h2>Historia Espiritual - Detalles</h2></center>

<div>
    <h4>HistoriaEspiritual</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaConversion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaConversion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaBautismo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaBautismo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Iglesia.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Iglesia.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Miembros.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Miembros.Nombres)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdMiembro }, new { @class = "btn btn-success" }) &nbsp;&nbsp;
    <a href="@Url.Action("Index","HistoriaEspirituals")" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</p>

CampDios/CampDios/Views/HistoriaEspirituals/Edit.cshtml
@model CampDios.Modelos.HistoriaEspiritual

@{
    ViewBag.Title = "Historia Espiritual - Editar";
}

<center><h2>Historia Espiritual - Editar</h2></center>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HistoriaEspiritual</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdHistoria)

        <div class="form-group">
            @Html.LabelFor(model => model.IdMiembro, "IdMiembro", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdMiembro", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdMiembro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaConversion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaConversion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaConversion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaBautismo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaBautismo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaBautismo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IglesiaBautismo, "IglesiaBautismo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IglesiaBautismo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IglesiaBautismo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CampDios/CampDios/Views/HistoriaEspirituals/Index.cshtml
@model IEnumerable<CampDios.Modelos.HistoriaEspiritual>

@{
    ViewBag.Title = "Historia espiritual - Inicio";
}

<center><h2>Historia espiritual - Inicio</h2></center>

<p>
    <a href="@Url.Action("Create","HistoriaEspirituals")" class="btn btn-primary"><i class="fa fa-plus-square fa-lg" aria-hidden="true"></i> Nueva historia espiritual</a>&nbsp;
    <a href="@Url.Action("Index","Miembros")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Miembros</a>&nbsp;
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FechaConversion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaBautismo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Iglesia.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Miembros.Nombres)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FechaConversion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaBautismo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Iglesia.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Miembros.Nombres)
        </td>
             <td>@Html.ActionLink("Editar", "Edit", new { id = item.IdHistoria }, new { @class = "btn btn-success" })</td>
        <td>@Html.ActionLink("Detalles", "Details", null, new { id = item.IdHistoria }, new { @class = "btn btn-info" })</td>
        <td>@Html.ActionLink("Borrar", "Delete", null, new { id = item.IdHistoria }, new { @class = "btn btn-danger" })</td> 
    </tr>
}

</table>