CampDios/CampDios/Controllers/ModulosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class ModulosController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Modulos
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Index()
        {
            return View(db.Modulos.ToList());
        }

        // GET: Modulos/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulos modulos = db.Modulos.Find(id);
            if (modulos == null)
            {
                return HttpNotFound();
            }
            return View(modulos);
        }

        // GET: Modulos/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Escritura")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Modulos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Modulos_Id,Nombre_Modulos")] Modulos modulos)
        {
            if (ModelState.IsValid)
            {
                db.Modulos.Add(modulos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(modulos);
        }

        // GET: Modulos/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulos modulos = db.Modulos.Find(id);
            if (modulos == null)
            {
                return HttpNotFound();
            }
            return View(modulos);
        }

        // POST: Modulos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Modulos_Id,Nombre_Modulos")] Modulos modulos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(modulos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(modulos);
        }

        // GET: Modulos/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulos modulos = db.Modulos.Find(id);
            if (modulos == null)
            {
                return HttpNotFound();
            }
            return View(modulos);
        }

        // POST: Modulos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Modulos modulos = db.Modulos.Find(id);
            db.Modulos.Remove(modulos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Controllers/OpcionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class OpcionesController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Opciones
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Index()
        {
            var opciones = db.Opciones.Include(o => o.Modulos);
            return View(opciones.ToList());
        }

        // GET: Opciones/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opciones opciones = db.Opciones.Find(id);
            if (opciones == null)
            {
                return HttpNotFound();
            }
            return View(opciones);
        }

        // GET: Opciones/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Escritura")]
        public ActionResult Create()
        {
            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos");
            return View();
        }

        // POST: Opciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Opciones_Id,Nombre_Opciones,Modulos_Modulos_Id")] Opciones opciones)
        {
            if (ModelState.IsValid)
            {
                db.Opciones.Add(opciones);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos", opciones.Modulos_Modulos_Id);
            return View(opciones);
        }

        // GET: Opciones/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opciones opciones = db.Opciones.Find(id);
            if (opciones == null)
            {
                return HttpNotFound();
            }
            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos", opciones.Modulos_Modulos_Id);
            return View(opciones);
        }

        // POST: Opciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Opciones_Id,Nombre_Opciones,Modulos_Modulos_Id")] Opciones opciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(opciones).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos", opciones.Modulos_Modulos_Id);
            return View(opciones);
        }

        // GET: Opciones/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opciones opciones = db.Opciones.Find(id);
            if (opciones == null)
            {
                return HttpNotFound();
            }
            return View(opciones);
        }

        // POST: Opciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Opciones opciones = db.Opciones.Find(id);
            db.Opciones.Remove(opciones);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Controllers/Usuarios_OpcionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class Usuarios_OpcionesController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Usuarios_Opciones
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Index()
        {
            var usuarios_Opciones = db.Usuarios_Opciones.Include(u => u.Opciones).Include(u => u.Usuarios);
            return View(usuarios_Opciones.ToList());
        }

        // GET: Usuarios_Opciones/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios_Opciones usuarios_Opciones = db.Usuarios_Opciones.Find(id);
            if (usuarios_Opciones == null)
            {
                return HttpNotFound();
            }
            return View(usuarios_Opciones);
        }

        // GET: Usuarios_Opciones/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Escritura")]
        public ActionResult Create()
        {
            ViewBag.Opciones_Opciones_Id = new SelectList(db.Opciones, "Opciones_Id", "Nombre_Opciones");
            ViewBag.Usuarios_Usuario_Id = new SelectList(db.Usuarios, "Usuarios_id", "Login");
            return View();
        }

        // POST: Usuarios_Opciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idUsuario_Opciones,Usuarios_Usuario_Id,Opciones_Opciones_Id,Lectura,Escritura,Edicion")] Usuarios_Opciones usuarios_Opciones)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios_Opciones.Add(usuarios_Opciones);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Opciones_Opciones_Id = new SelectList(db.Opciones, "Opciones_Id", "Nombre_Opciones", usuarios_Opciones.Opciones_Opciones_Id);
            ViewBag.Usuarios_Usuario_Id = new SelectList(db.Usuarios, "Usuarios_id", "Login", usuarios_Opciones.Usuarios_Usuario_Id);
            return View(usuarios_Opciones);
        }

        // GET: Usuarios_Opciones/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios_Opciones usuarios_Opciones = db.Usuarios_Opciones.Find(id);
            if (usuarios_Opciones == null)
            {
                return HttpNotFound();
            }
            ViewBag.Opciones_Opciones_Id = new SelectList(db.Opciones, "Opciones_Id", "Nombre_Opciones", usuarios_Opciones.Opciones_Opciones_Id);
            ViewBag.Usuarios_Usuario_Id = new SelectList(db.Usuarios, "Usuarios_id", "Login", usuarios_Opciones.Usuarios_Usuario_Id);
            return View(usuarios_Opciones);
        }

        // POST: Usuarios_Opciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idUsuario_Opciones,Usuarios_Usuario_Id,Opciones_Opciones_Id,Lectura,Escritura,Edicion")] Usuarios_Opciones usuarios_Opciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuarios_Opciones).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Opciones_Opciones_Id = new SelectList(db.Opciones, "Opciones_Id", "Nombre_Opciones", usuarios_Opciones.Opciones_Opciones_Id);
            ViewBag.Usuarios_Usuario_Id = new SelectList(db.Usuarios, "Usuarios_id", "Login", usuarios_Opciones.Usuarios_Usuario_Id);
            return View(usuarios_Opciones);
        }

        // GET: Usuarios_Opciones/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios_Opciones usuarios_Opciones = db.Usuarios_Opciones.Find(id);
            if (usuarios_Opciones == null)
            {
                return HttpNotFound();
            }
            return View(usuarios_Opciones);
        }

        // POST: Usuarios_Opciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuarios_Opciones usuarios_Opciones = db.Usuarios_Opciones.Find(id);
            db.Usuarios_Opciones.Remove(usuarios_Opciones);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Views/Usuarios_Opciones/Create.cshtml
@model CampDios.Modelos.Usuarios_Opciones

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuarios Permisos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Usuarios_Usuario_Id, "Usuarios_Usuario_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Usuarios_Usuario_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Usuarios_Usuario_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opciones_Opciones_Id, "Opciones_Opciones_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Opciones_Opciones_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Opciones_Opciones_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lectura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Lectura)
                    @Html.ValidationMessageFor(model => model.Lectura, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Escritura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Escritura)
                    @Html.ValidationMessageFor(model => model.Escritura, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Edicion)
                    @Html.ValidationMessageFor(model => model.Edicion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","Usuarios_Opciones")" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</div>

CampDios/CampDios/Views/Usuarios_Opciones/Delete.cshtml
@model CampDios.Modelos.Usuarios_Opciones

@{
    ViewBag.Title = "Borrar Usuarios_Opciones";
}

<h2>Eliminar</h2>

<h3>¿Esta seguro que desea eliminar este Permiso de este usuario</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lectura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lectura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Escritura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Escritura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edicion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opciones.Nombre_Opciones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opciones.Nombre_Opciones)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuarios.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuarios.Login)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> &nbsp;&nbsp;
            <a href="@Url.Action("Index","Usuarios_Opciones")" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
            </a>
        </div>
    }
</div>

CampDios/CampDios/Views/Usuarios_Opciones/Details.cshtml
@model CampDios.Modelos.Usuarios_Opciones

@{
    ViewBag.Title = "Usuarios_Opciones-Detlles";
}

<h2>Detalles</h2>

<div>
    <h4>Permisos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lectura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lectura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Escritura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Escritura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edicion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opciones.Nombre_Opciones)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opciones.Nombre_Opciones)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuarios.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuarios.Login)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.idUsuario_Opciones }, new { @class = "btn btn-success" }) &nbsp;&nbsp;
    <a href="javascript:history.back();" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</p>

CampDios/CampDios/Views/Usuarios_Opciones/Edit.cshtml
@model CampDios.Modelos.Usuarios_Opciones

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuarios Permisos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idUsuario_Opciones)

        <div class="form-group">
            @Html.LabelFor(model => model.Usuarios_Usuario_Id, "Usuarios_Usuario_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Usuarios_Usuario_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Usuarios_Usuario_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opciones_Opciones_Id, "Opciones_Opciones_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Opciones_Opciones_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Opciones_Opciones_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lectura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Lectura)
                    @Html.ValidationMessageFor(model => model.Lectura, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Escritura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Escritura)
                    @Html.ValidationMessageFor(model => model.Escritura, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Edicion)
                    @Html.ValidationMessageFor(model => model.Edicion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="javascript:history.back();" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</div>

CampDios/CampDios/Views/Usuarios_Opciones/Index.cshtml
@model IEnumerable<CampDios.Modelos.Usuarios_Opciones>

@{
    ViewBag.Title = "Index";
}

<h2>Administración de Permisos por Usuario </h2>

<p>
    <a href="@Url.Action("Create","Usuarios_Opciones")" class="btn btn-primary"><i class="fa fa-plus-square fa-lg" aria-hidden="true"></i>Nuevo Permiso</a>&nbsp;
    <a href="@Url.Action("Index","Usuarios")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Usuarios</a>&nbsp;
    <a href="@Url.Action("Index","Modulos")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Módulos</a>&nbsp;
    <a href="@Url.Action("Index","Opciones")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Opciones(Vistas)</a>&nbsp;

</p>
<table class="table">
    <tr>
        <th>
            <h5><strong>Lectura</strong></h5>
        </th>
        <th>
            <h5><strong>Escritura</strong></h5>
        </th>
        <th>
            <h5><strong>Edición</strong></h5>
        </th>
        <th>
            <h5><strong>Opciones - Vistas</strong></h5>
        </th>
        <th>
            <h5><strong>Login - Nombre de usuario</strong></h5>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Lectura)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Escritura)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edicion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opciones.Nombre_Opciones)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Usuarios.Login)
        </td>

        <td>@Html.ActionLink("Editar", "Edit", new { id = item.idUsuario_Opciones }, new { @class = "btn btn-success" })</td>
        <td>@Html.ActionLink("Detalles", "Details", null, new { id = item.idUsuario_Opciones }, new { @class = "btn btn-info" })</td>
        <td>@Html.ActionLink("Borrar", "Delete", null, new { id = item.idUsuario_Opciones }, new { @class = "btn btn-danger" })</td>

    </tr>
}

</table>