CampDios/CampDios/Controllers/ComunidadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class ComunidadController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Comunidad
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Comunidad", Permiso = "Lectura")]
        public ActionResult Index()
        {
            var comunidad = db.Comunidad.Include(c => c.Miembros).Include(c => c.Zona);
            return View(comunidad.ToList());
        }


        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Comunidad", Permiso = "Lectura")]
        // GET: Comunidad/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comunidad comunidad = db.Comunidad.Find(id);
            if (comunidad == null)
            {
                return HttpNotFound();
            }
            return View(comunidad);
        }

        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Comunidad", Permiso = "Lectura")]
        public ActionResult GrupoDetalle(int? id)
        {
            var grupo = db.Grupo.Where(g => g.IdComunidad == id);
            return View(grupo);
            
        }

        // GET: Comunidad/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Comunidad", Permiso = "Escritura")]
        public ActionResult Create()
        {
            /*var result = db.Database.SqlQuery<seleccionar_lider_Result1>("exec seleccionar_lider"); //llamando al procedimiento almacenado "seleccionar_lider"
            ViewBag.IdLiderComunidad = new SelectList(result.ToList(), "IdMiembro", "Nombres"); // pasando lo que viene del Stored Procedure a el dropdown*/
            //ViewBag.IdLiderComunidad = new SelectList(db.Miembros, "IdMiembro", "Nombres");
            var result = db.Database.SqlQuery<seleccionar_lider_Result>("exec seleccionar_lider"); //llamando al procedimiento almacenado "seleccionar_lider"
            ViewBag.IdLiderComunidad = new SelectList(result.ToList(), "IdMiembro","Nombres"); // pasando lo que viene del Stored Procedure a el dropdown
            ViewBag.IdZona = new SelectList(db.Zona, "IdZona", "Nombre");
            return View();
        }

        // POST: Comunidad/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdComunidad,Nombre,Descripcion,Direccion,IdLiderComunidad,IdZona")] Comunidad comunidad)
        {
            if (ModelState.IsValid)
            {
                db.Comunidad.Add(comunidad);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.IdLiderComunidad = new SelectList(db.Miembros, "IdMiembro", "Nombres", comunidad.IdLiderComunidad);
            ViewBag.IdZona = new SelectList(db.Zona, "IdZona", "Nombre", comunidad.IdZona);
            return View(comunidad);
        }
        
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Comunidad", Permiso = "Editar")]
        // GET: Comunidad/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comunidad comunidad = db.Comunidad.Find(id);
            if (comunidad == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdLiderComunidad = new SelectList(db.Miembros, "IdMiembro", "Nombres", comunidad.IdLiderComunidad);
            ViewBag.IdZona = new SelectList(db.Zona, "IdZona", "Nombre", comunidad.IdZona);
            return View(comunidad);
        }

        // POST: Comunidad/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdComunidad,Nombre,Descripcion,Direccion,IdLiderComunidad,IdZona")] Comunidad comunidad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comunidad).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdLiderComunidad = new SelectList(db.Miembros, "IdMiembro", "Nombres", comunidad.IdLiderComunidad);
            ViewBag.IdZona = new SelectList(db.Zona, "IdZona", "Nombre", comunidad.IdZona);
            return View(comunidad);
        }
        
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Comunidad", Permiso = "Edicion")]
        // GET: Comunidad/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comunidad comunidad = db.Comunidad.Find(id);
            if (comunidad == null)
            {
                return HttpNotFound();
            }
            return View(comunidad);
        }

        // POST: Comunidad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comunidad comunidad = db.Comunidad.Find(id);
            db.Comunidad.Remove(comunidad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
         
    }
}

CampDios/CampDios/Controllers/DetalleGrupoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class DetalleGrupoController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: DetalleGrupo
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupo", Permiso = "Lectura")]
        public ActionResult Index()
        {
            var detalleGrupo = db.DetalleGrupo.Include(d => d.Grupo).Include(d => d.Miembros);
            return View(detalleGrupo.ToList());
        }

        // GET: DetalleGrupo/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupo", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleGrupo detalleGrupo = db.DetalleGrupo.Find(id);
            if (detalleGrupo == null)
            {
                return HttpNotFound();
            }
            return View(detalleGrupo);
        }

        // GET: DetalleGrupo/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupo", Permiso = "Escritura")]
        public ActionResult Create()
        {
            ViewBag.IdGrupo = new SelectList(db.Grupo, "IdGrupo", "Nombre");
            //ViewBag.IdMiembro = new SelectList(db.seleccionar_lider_grupo());
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres");
            return View();
        }

        // POST: DetalleGrupo/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdDetalleGrupo,IdGrupo,IdMiembro")] DetalleGrupo detalleGrupo)
        {
            if (ModelState.IsValid)
            {
                db.DetalleGrupo.Add(detalleGrupo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdGrupo = new SelectList(db.Grupo, "IdGrupo", "Nombre", detalleGrupo.IdGrupo);
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres", detalleGrupo.IdMiembro);
            return View(detalleGrupo);
        }

        // GET: DetalleGrupo/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Parentesco", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleGrupo detalleGrupo = db.DetalleGrupo.Find(id);
            if (detalleGrupo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdGrupo = new SelectList(db.Grupo, "IdGrupo", "Nombre", detalleGrupo.IdGrupo);
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres", detalleGrupo.IdMiembro);
            return View(detalleGrupo);
        }

        // POST: DetalleGrupo/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdDetalleGrupo,IdGrupo,IdMiembro")] DetalleGrupo detalleGrupo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detalleGrupo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdGrupo = new SelectList(db.Grupo, "IdGrupo", "Nombre", detalleGrupo.IdGrupo);
            ViewBag.IdMiembro = new SelectList(db.Miembros, "IdMiembro", "Nombres", detalleGrupo.IdMiembro);
            return View(detalleGrupo);
        }

        // GET: DetalleGrupo/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Parentesco", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetalleGrupo detalleGrupo = db.DetalleGrupo.Find(id);
            if (detalleGrupo == null)
            {
                return HttpNotFound();
            }
            return View(detalleGrupo);
        }

        // POST: DetalleGrupo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DetalleGrupo detalleGrupo = db.DetalleGrupo.Find(id);
            db.DetalleGrupo.Remove(detalleGrupo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Controllers/GrupoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class GrupoController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Grupo
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupos", Permiso = "Lectura")]
        public ActionResult Index()
        {
            var grupo = db.Grupo.Include(g => g.Comunidad).Include(g => g.Dias).Include(g => g.Tipo_Grupo);
            return View(grupo.ToList());
        }

        // GET: Grupo/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupos", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupo grupo = db.Grupo.Find(id);
            if (grupo == null)
            {
                return HttpNotFound();
            }
            return View(grupo);
        }

        // GET: Grupo/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupos", Permiso = "Escritura")]
        public ActionResult Create()
        {
            ViewBag.IdComunidad = new SelectList(db.Comunidad, "IdComunidad", "Nombre");
            ViewBag.IdDia = new SelectList(db.Dias, "IdDia", "Dia");
            ViewBag.IdTipoGrupo = new SelectList(db.Tipo_Grupo, "IdTipoGrupo", "Descripcion");
            return View();
        }

        // POST: Grupo/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdGrupo,Nombre,Descripcion,Direccion,IdComunidad,IdDia,Hora,IdTipoGrupo")] Grupo grupo)
        {
            if (ModelState.IsValid)
            {
                db.Grupo.Add(grupo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdComunidad = new SelectList(db.Comunidad, "IdComunidad", "Nombre", grupo.IdComunidad);
            ViewBag.IdDia = new SelectList(db.Dias, "IdDia", "Dia", grupo.IdDia);
            ViewBag.IdTipoGrupo = new SelectList(db.Tipo_Grupo, "IdTipoGrupo", "Descripcion", grupo.IdTipoGrupo);
            return View(grupo);
        }

        // GET: Grupo/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupos", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupo grupo = db.Grupo.Find(id);
            if (grupo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdComunidad = new SelectList(db.Comunidad, "IdComunidad", "Nombre", grupo.IdComunidad);
            ViewBag.IdDia = new SelectList(db.Dias, "IdDia", "Dia", grupo.IdDia);
            ViewBag.IdTipoGrupo = new SelectList(db.Tipo_Grupo, "IdTipoGrupo", "Descripcion", grupo.IdTipoGrupo);
            return View(grupo);
        }

        // POST: Grupo/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdGrupo,Nombre,Descripcion,Direccion,IdComunidad,IdDia,Hora,IdTipoGrupo")] Grupo grupo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(grupo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdComunidad = new SelectList(db.Comunidad, "IdComunidad", "Nombre", grupo.IdComunidad);
            ViewBag.IdDia = new SelectList(db.Dias, "IdDia", "Dia", grupo.IdDia);
            ViewBag.IdTipoGrupo = new SelectList(db.Tipo_Grupo, "IdTipoGrupo", "Descripcion", grupo.IdTipoGrupo);
            return View(grupo);
        }

        // GET: Grupo/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Grupos", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupo grupo = db.Grupo.Find(id);
            if (grupo == null)
            {
                return HttpNotFound();
            }
            return View(grupo);
        }

        // POST: Grupo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Grupo grupo = db.Grupo.Find(id);
            db.Grupo.Remove(grupo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Views/Comunidad/Create.cshtml
@model CampDios.Modelos.Comunidad

@{
    ViewBag.Title = "Comunidad-Crear";
}

<center><h2>Comunidad-Crear</h2></center>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal"> 
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control",required="required" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdLiderComunidad, "IdLiderComunidad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLiderComunidad", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLiderComunidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdZona, "IdZona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdZona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdZona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","Comunidad")" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CampDios/CampDios/Views/Comunidad/Delete.cshtml
@model CampDios.Modelos.Comunidad

@{
    ViewBag.Title = "Comunidad-Borrar";
}

<center><h2>Comunidad-Borrar</h2></center>

<h3>¿Esta seguro que desea borrar esta comunidad?</h3>
<div> 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Miembros.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Miembros.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zona.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zona.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> &nbsp;&nbsp;
            <a href="@Url.Action("Index","Comunidad")" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
            </a>
        </div>
    }
</div>

CampDios/CampDios/Views/Comunidad/Details.cshtml
@model CampDios.Modelos.Comunidad

@{
    ViewBag.Title = "Details";
}

<center><h2>Detalles</h2></center>

<div>
    <center><h4>Comunidad</h4></center>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Miembros.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Miembros.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zona.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zona.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdComunidad }, new { @class = "btn btn-success" }) &nbsp;&nbsp;
    <a href="javascript:history.back();" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</p>

CampDios/CampDios/Views/Comunidad/GrupoDetalle.cshtml
@model IEnumerable<CampDios.Modelos.Grupo>

@{
    ViewBag.Title = "GrupoDetalle";
}

<h2>GrupoDetalle</h2>


<p>
    <a href="@Url.Action("Create","Grupo")" class="btn btn-primary"><i class="fa fa-plus-square fa-lg" aria-hidden="true"></i> Nuevo grupo</a>&nbsp;
    <a href="@Url.Action("Index","DetalleGrupo")" class="btn btn-success"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Miembros de grupos</a>&nbsp;
    <a href="@Url.Action("Index","Zonas")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Zonas</a>&nbsp;
    <a href="@Url.Action("Index","Comunidad")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Comunidades</a>&nbsp;
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora)
        </th>
        <th>
            Comunidad
            <!--@Html.DisplayNameFor(model => model.Comunidad.Nombre)-->
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dias.Dia)
        </th>
        <th>
            Tipo de grupo
            <!--@Html.DisplayNameFor(model => model.Tipo_Grupo.Descripcion)-->
        </th>
        <th></th>
        <th>Opciones</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comunidad.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dias.Dia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo_Grupo.Descripcion)
            </td>
            <td>@Html.ActionLink("Editar", "Edit", new { id = item.IdGrupo }, new { @class = "btn btn-success" })</td>
            <td>@Html.ActionLink("Detalles", "Details", null, new { id = item.IdGrupo }, new { @class = "btn btn-info" })</td>
            <td>@Html.ActionLink("Borrar", "Delete", null, new { id = item.IdGrupo }, new { @class = "btn btn-danger" })</td>
        </tr>
    }
</table>