CampDios/CampDios/Controllers/ModulosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class ModulosController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Modulos
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Index()
        {
            return View(db.Modulos.ToList());
        }

        // GET: Modulos/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulos modulos = db.Modulos.Find(id);
            if (modulos == null)
            {
                return HttpNotFound();
            }
            return View(modulos);
        }

        // GET: Modulos/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Escritura")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Modulos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Modulos_Id,Nombre_Modulos")] Modulos modulos)
        {
            if (ModelState.IsValid)
            {
                db.Modulos.Add(modulos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(modulos);
        }

        // GET: Modulos/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulos modulos = db.Modulos.Find(id);
            if (modulos == null)
            {
                return HttpNotFound();
            }
            return View(modulos);
        }

        // POST: Modulos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Modulos_Id,Nombre_Modulos")] Modulos modulos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(modulos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(modulos);
        }

        // GET: Modulos/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Modulos modulos = db.Modulos.Find(id);
            if (modulos == null)
            {
                return HttpNotFound();
            }
            return View(modulos);
        }

        // POST: Modulos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Modulos modulos = db.Modulos.Find(id);
            db.Modulos.Remove(modulos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Controllers/OpcionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class OpcionesController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Opciones
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Index()
        {
            var opciones = db.Opciones.Include(o => o.Modulos);
            return View(opciones.ToList());
        }

        // GET: Opciones/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opciones opciones = db.Opciones.Find(id);
            if (opciones == null)
            {
                return HttpNotFound();
            }
            return View(opciones);
        }

        // GET: Opciones/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Escritura")]
        public ActionResult Create()
        {
            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos");
            return View();
        }

        // POST: Opciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Opciones_Id,Nombre_Opciones,Modulos_Modulos_Id")] Opciones opciones)
        {
            if (ModelState.IsValid)
            {
                db.Opciones.Add(opciones);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos", opciones.Modulos_Modulos_Id);
            return View(opciones);
        }

        // GET: Opciones/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opciones opciones = db.Opciones.Find(id);
            if (opciones == null)
            {
                return HttpNotFound();
            }
            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos", opciones.Modulos_Modulos_Id);
            return View(opciones);
        }

        // POST: Opciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Opciones_Id,Nombre_Opciones,Modulos_Modulos_Id")] Opciones opciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(opciones).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Modulos_Modulos_Id = new SelectList(db.Modulos, "Modulos_Id", "Nombre_Modulos", opciones.Modulos_Modulos_Id);
            return View(opciones);
        }

        // GET: Opciones/Delete/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opciones opciones = db.Opciones.Find(id);
            if (opciones == null)
            {
                return HttpNotFound();
            }
            return View(opciones);
        }

        // POST: Opciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Opciones opciones = db.Opciones.Find(id);
            db.Opciones.Remove(opciones);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampDios.Modelos;

namespace CampDios.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private CampDiosEntities db = new CampDiosEntities();

        // GET: Usuarios
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuarios/Details/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Lectura")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // GET: Usuarios/Create
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Escritura")]
        public ActionResult Create()
        {
            ViewBag.Miembro_Id = new SelectList(db.Miembros, "IdMiembro", "Nombres");
            return View();
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Usuarios_id,Login,Contraseña,Fecha_creacion,Miembro_id")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuarios);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Miembro_Id = new SelectList(db.Miembros, "IdMiembro", "Nombres", usuarios.Miembro_id);
            return View(usuarios);
        }

        // GET: Usuarios/Edit/5
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            ViewBag.Miembro_Id = new SelectList(db.Miembros, "IdMiembro", "Nombres");
            return View(usuarios);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Usuarios_id,Login,Contraseña,Fecha_creacion,Miembro_id")] Usuarios usuarios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuarios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Miembro_Id = new SelectList(db.Miembros, "IdMiembro", "Nombres", usuarios.Miembro_id);
            return View(usuarios);
        }

        // GET: Usuarios/Delete/
        [AuthorizeUserAccesLevel(UserRole = true, Vista = "Administrador", Permiso = "Edicion")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuarios usuarios = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuarios);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CampDios/CampDios/Views/Modulos/Create.cshtml
@model CampDios.Modelos.Modulos

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Modulos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_Modulos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Modulos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Modulos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index","Modulos")" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</div>

CampDios/CampDios/Views/Modulos/Delete.cshtml
@model CampDios.Modelos.Modulos

@{
    ViewBag.Title = "Borrar Modulo";
}

<h2>Eliminar</h2>

<h3>¿Esta seguro que desea eliminar este Módulo?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_Modulos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_Modulos)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> &nbsp;&nbsp;
            <a href="@Url.Action("Index","Modulos")" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
            </a>
        </div>
    }
</div>

CampDios/CampDios/Views/Modulos/Details.cshtml
@model CampDios.Modelos.Modulos

@{
    ViewBag.Title = "Modulo-Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Módulos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_Modulos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_Modulos)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Modulos_Id }, new { @class = "btn btn-success" }) &nbsp;&nbsp;
    <a href="javascript:history.back();" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</p>

CampDios/CampDios/Views/Modulos/Edit.cshtml
@model CampDios.Modelos.Modulos

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Módulos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Modulos_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_Modulos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Modulos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Modulos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="javascript:history.back();" class="btn btn-default">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Volver al listado
    </a>
</div>

CampDios/CampDios/Views/Modulos/Index.cshtml
@model IEnumerable<CampDios.Modelos.Modulos>

@{
    ViewBag.Title = "Index";
}

<h2>Administración de Módulos</h2>

<p>
    <a href="@Url.Action("Create","Modulos")" class="btn btn-primary"><i class="fa fa-plus-square fa-lg" aria-hidden="true"></i> Nuevo Módulo</a>&nbsp;
    <a href="@Url.Action("Index","Usuarios")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Usuarios</a>&nbsp;
    <a href="@Url.Action("Index","Opciones")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Opciones(Vistas)</a>&nbsp;
    <a href="@Url.Action("Index","Usuarios_Opciones")" class="btn btn-default"><i class="fa fa-book fa-lg" aria-hidden="true"></i> Permisos</a>&nbsp;
</p>
<table class="table">
    <tr>
        <th>
            <h5><strong>Módulos</strong></h5>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre_Modulos)
        </td>
        
        <td>@Html.ActionLink("Editar", "Edit", new { id = item.Modulos_Id }, new { @class = "btn btn-success" })</td>
        <td>@Html.ActionLink("Detalles", "Details", null, new { id = item.Modulos_Id }, new { @class = "btn btn-info" })</td>
        <td>@Html.ActionLink("Borrar", "Delete", null, new { id = item.Modulos_Id }, new { @class = "btn btn-danger" })</td>
    </tr>
}

</table>